name: Test sofa-setup-action

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  run:
    name: Run on ${{ matrix.os }} with SOFA ${{ matrix.sofa_branch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
        sofa_branch: [master, v21.06, v21.12, v22.06, v22.12, v23.06]

    steps:
      - name: Setup SOFA and deps
        id: sofa
        uses: sofa-framework/sofa-setup-action@master
        with:
          sofa_version: ${{ matrix.sofa_branch }}
          sofa_root: ${{ github.workspace }}/sofa

      - name: Print sofa-setup-action outputs
        shell: bash
        run: |
          echo 'steps.sofa.outputs = ${{ toJSON(steps.sofa.outputs) }}'
          echo "----------------------------"
          ls -la '${{ steps.sofa.outputs.sofa_root }}'
          echo "----------------------------"
          echo "PATH = $PATH"
          echo "----------------------------"
          echo "SOFA_ROOT = $SOFA_ROOT"
          echo "----------------------------"
          echo "----------------------------"
          echo 'github.path = ${{ toJSON(github.path) }}'
          echo "----------------------------"
          ls -la '${{ runner.temp }}'
          echo "----------------------------"
          ls -la '${{ runner.temp }}'/_runner_file_commands/add_path*
          echo "----------------------------"
          cat '${{ runner.temp }}'/_runner_file_commands/add_path*
          echo "----------------------------"
          
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "----------------------------"
            cmd //c 'echo EIGEN3_ROOT=%EIGEN3_ROOT%'
            cmd //c 'echo Eigen3_ROOT=%Eigen3_ROOT%'
            cmd //c 'echo BOOST_ROOT=%BOOST_ROOT%'
            cmd //c 'echo Boost_ROOT=%Boost_ROOT%'
            echo "----------------------------"
            cmd //c 'echo PATH=%PATH%'
          fi
